name: Build and Release OnePlus Kernels

permissions:
  contents: write
  actions: write
  workflows: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: true
      build_sm8450:
        description: 'Build sm8450 (10Pro)?'
        required: true
        type: boolean
        default: true
      build_sm8475:
        description: 'Build sm8475 (10t, 11r, Ace2)?'
        required: true
        type: boolean
        default: true
      build_sm8550:
        description: 'Build sm8550 (11, Open, Ace2Pro)?'
        required: true
        type: boolean
        default: true
      build_sm8650:
        description: 'Build sm8750 (12, 13r, Ace5)?'
        required: true
        type: boolean
        default: true
      build_sm8750:
        description: 'Build sm8750 (13, Ace5Pro)?'
        required: true
        type: boolean
        default: true
      build_sm7675:
        description: 'Build sm7675 (Nord4)?'
        required: true
        type: boolean
        default: true

jobs:
  build-sm8450:
    if: ${{ inputs.build_sm8450 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP10pro
            soc: waipio
            branch: oneplus/sm8450
            manifest: oneplus_10_pro_v.xml
            android_version: android12
            kernel_version: "5.10"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      
  build-sm8475:
    if: ${{ inputs.build_sm8475 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP10t
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_10t_v.xml
            android_version: android12
            kernel_version: "5.10"
          - model: OP11r
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_11r_v.xml
            android_version: android13
            kernel_version: "5.10"
          - model: OPACE2
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_ace2_v.xml
            android_version: android13
            kernel_version: "5.10"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      
  build-sm8550:
    if: ${{ inputs.build_sm8550 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP11
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_11_v.xml
            android_version: android13
            kernel_version: "5.15"
          - model: OPOPEN
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_open_v.xml
            android_version: android13
            kernel_version: "5.15"
          - model: OPACE2PRO
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_ace2pro_v.xml
            android_version: android13
            kernel_version: "5.15"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      
  build-sm8650:
    if: ${{ inputs.build_sm8650 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP12
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus12_v.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP13r
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_13r.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OPACE5
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_ace5.xml
            android_version: android14
            kernel_version: "6.1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}

  build-sm8750:
    if: ${{ inputs.build_sm8750 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP13
            soc: sun
            branch: oneplus/sm8750
            manifest: JiuGeFaCai_oneplus_13_v.xml
            android_version: android15
            kernel_version: "6.6"
          - model: OPAce5Pro
            soc: sun
            branch: oneplus/sm8750
            manifest: JiuGeFaCai_oneplus_ace5_pro_v.xml
            android_version: android15
            kernel_version: "6.6"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      
  build-sm7675:
    if: ${{ inputs.build_sm7675 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OPNORD4
            soc: pineapple
            branch: oneplus/sm7675
            manifest: oneplus_nord_4_v.xml
            android_version: android14
            kernel_version: "6.1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      model: ${{ matrix.model }}
      soc: ${{ matrix.soc }}
      branch: ${{ matrix.branch }}
      manifest: ${{ matrix.manifest }}
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}

  trigger-release:
    needs:
      - build-sm8450
      - build-sm8475
      - build-sm8550
      - build-sm8650
      - build-sm8750
      - build-sm7675
    runs-on: ubuntu-latest
    if: ${{ inputs.make_release }}
    env:
      REPO_OWNER: luigimak
      REPO_NAME: OP_KSUNext_SUSFS
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "*TEST BUILD* OnePlus Kernels with KernelSU Next & SUSFS *TEST BUILD*"
#      RELEASE_NOTES: |
      
#        Module SUSFS: 
#        -> https://github.com/sidex15/ksu_module_susfs

#        KernelSU-Next Managers:
#        -> https://github.com/KernelSU-Next/KernelSU-Next

#        Features:
#        [+] KernelSU-Next
#        [+] SUSFS v1.5.5
#        [+] Wireguard Support
#        [+] Maphide LineageOS Detections
#        [+] Futile Maphide for jit-zygote-cache Detections
#        [+] Magic Mount Support

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download KernelSU Version
        uses: actions/download-artifact@v4
        with:
          name: kernelsu-version
          path: ./ksu

      - name: Read KernelSU Version
        run: |
          KSUVER=$(cat ./ksu/ksuver.txt)
          echo "KSUVER=$KSUVER"
          echo "KSUVER=$KSUVER" >> $GITHUB_ENV

      - name: Set dynamic RELEASE_NOTES
        run: |
          echo "RELEASE_NOTES=Module SUSFS:%0A-> https://github.com/sidex15/ksu_module_susfs%0A" >> $GITHUB_ENV
          echo "RELEASE_NOTES+=%0AKernelSU-Next Managers:%0A-> https://github.com/KernelSU-Next/KernelSU-Next%0A" >> $GITHUB_ENV
          echo "RELEASE_NOTES+=%0AFeatures:%0A[+] KernelSU-Next v${KSUVER}%0A[+] SUSFS v1.5.5%0A[+] Wireguard Support%0A[+] Maphide LineageOS Detections%0A[+] Futile Maphide for jit-zygote-cache Detections%0A[+] Magic Mount Support" >> $GITHUB_ENV


      - name: Generate and Create New Tag
        run: |
          KSUVER="${{ env.KSUVER }}"

          EXISTING=$(gh api repos/$REPO_OWNER/$REPO_NAME/tags --jq '.[].name' | grep "^$KSUVER" || true)

          if [ -z "$EXISTING" ]; then
            NEW_TAG="${KSUVER}-r0"
          else
            LAST_SUFFIX=$(echo "$EXISTING" | sed "s/^${KSUVER}-r//" | sort -n | tail -n1)
            NEW_TAG="${KSUVER}-r$((LAST_SUFFIX + 1))"
          fi

          echo "✅ Generated tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }}.git
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: true
          release_name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_NOTES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Release Assets Dynamically
        run: |
          for file in ./downloaded-artifacts/kernel-*/*; do
              if [ -d "$file" ]; then
                  continue
              fi
              echo "Uploading $file..."
              gh release upload ${{ env.NEW_TAG }} "$file"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NEW_TAG: ${{ env.NEW_TAG }}

      - name: Display Files Uploaded
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*
